// <auto-generated />
using System;
using Car.Demo.DLL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Car.Demo.Migrations
{
    [DbContext(typeof(CarDbContext))]
    partial class CarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.2.22153.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Car.Demo.DLL.Entities.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca0cde35-50b0-49e5-8534-f0aa08115d76"),
                            Brand = "Mercedes",
                            Country = "Germany",
                            Model = "CLS",
                            Price = 30000.0,
                            PublisherId = new Guid("dd2e3a6b-ec8f-4e9f-a72c-57e08f779f58")
                        },
                        new
                        {
                            Id = new Guid("73e35e11-ec5c-477b-a491-b8ce2bb5e922"),
                            Brand = "BMW",
                            Country = "Germany",
                            Model = "X5",
                            Price = 25000.0,
                            PublisherId = new Guid("dd2e3a6b-ec8f-4e9f-a72c-57e08f779f58")
                        },
                        new
                        {
                            Id = new Guid("7dc52b77-dbce-4fd7-b48a-069dbc2d5b40"),
                            Brand = "Audi",
                            Country = "Germany",
                            Model = "A5",
                            Price = 20000.0,
                            PublisherId = new Guid("dd2e3a6b-ec8f-4e9f-a72c-57e08f779f58")
                        });
                });

            modelBuilder.Entity("Car.Demo.DLL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastChanged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dd2e3a6b-ec8f-4e9f-a72c-57e08f779f58"),
                            Email = "c.basset@gmail.com",
                            HashPassword = "$2a$11$EQLIzSqPkfpkmSWICMqL3uxNw0DDL.eTHx6vrDCHKOR2XS0C06EdC",
                            LastChanged = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Celeste Bassett",
                            PhoneNumber = "0683006027",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("26af7842-53e0-4680-96cb-8c02a696e59f"),
                            Email = "l.wilkins@gmail.com",
                            HashPassword = "$2a$11$dd6boCqeH4WwfNuQy9o0m.diA73qUUkwyflNS2oLyCNfMXk1kgV0e",
                            LastChanged = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lacey Wilkins",
                            PhoneNumber = "0683006024",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("7e892c70-763f-456e-b392-cb9211e681d3"),
                            Email = "s.newman@gmail.com",
                            HashPassword = "$2a$11$ob2AfJ2iEH4UGhAlHWf/j.SKKRsdiejR.wLNk/Fq0eRBt9ld26pKm",
                            LastChanged = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Safwan Newman",
                            PhoneNumber = "0683006024",
                            Role = 3
                        });
                });

            modelBuilder.Entity("Car.Demo.DLL.Entities.Car", b =>
                {
                    b.HasOne("Car.Demo.DLL.Entities.User", "Publisher")
                        .WithMany("Cars")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Car.Demo.DLL.Entities.User", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
